<a href="https://colab.research.google.com/github/NileshPatil24-a/Deep_Learning/blob/main/constat_weight_Initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
df = sns.load_dataset('iris')

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [7]:
df.sample(5)

sepal_length  sepal_width  petal_length  petal_width  species
56            6.3          3.3           4.7          1.6        1
127           6.1          3.0           4.9          1.8        2
48            5.3          3.7           1.5          0.2        0
79            5.7          2.6           3.5          1.0        1
124           6.7          3.3           5.7          2.1        2

In [8]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [9]:
model = Sequential()
model.add(Dense(3, activation='relu', input_dim = 4))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
initial_weights = model.get_weights()


In [14]:
initial_weights

[array([[ 0.21242297,  0.5771918 ,  0.20843256],
        [-0.05558932, -0.44663677, -0.73265386],
        [ 0.20014238, -0.9251224 , -0.28010762],
        [-0.22057247,  0.1865853 ,  0.41716802]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.21067595],
        [-0.09641147],
        [ 0.13832653]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
initial_weights[0] = np.ones(initial_weights[0].shape)*0.5
initial_weights[1] = np.ones(initial_weights[1].shape)*0.5
initial_weights[2] = np.ones(initial_weights[2].shape)*0.5
initial_weights[3] = np.ones(initial_weights[3].shape)*0.5


In [20]:
initial_weights

[array([[0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]]),
 array([0.5, 0.5, 0.5]),
 array([[0.5],
        [0.5],
        [0.5]]),
 array([0.5])]

In [21]:
model.set_weights(initial_weights)

In [22]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1:].values

In [23]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
history = model.fit(X,y, epochs=100, validation_split=0.2)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - accuracy: 0.4229 - loss: 0.5830 - val_accuracy: 0.0000e+00 - val_loss: -14.0814
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4042 - loss: 1.4779 - val_accuracy: 0.0000e+00 - val_loss: -13.9788
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3990 - loss: 1.4656 - val_accuracy: 0.0000e+00 - val_loss: -13.8803
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4000 - loss: 1.2507 - val_accuracy: 0.0000e+00 - val_loss: -13.7847
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4073 - loss: 1.1146 - val_accuracy: 0.0000e+00 - val_loss: -13.6908
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4365 - loss: 1.6190 - val_accuracy: 0.0000e+00 - val_loss: -13.5854
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4073 - loss: 1.1447 - val_accuracy: 0.0000e+00 - val_loss: -13.4914
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3979 - loss:

In [26]:
model.get_weights()

[array([[0.20197564, 0.20197564, 0.20197564],
        [0.16498484, 0.16498484, 0.16498484],
        [0.72789645, 0.72789645, 0.72789645],
        [0.81579226, 0.81579226, 0.81579226]], dtype=float32),
 array([0.17364003, 0.17364003, 0.17364003], dtype=float32),
 array([[0.357095],
        [0.357095],
        [0.357095]], dtype=float32),
 array([0.14179005], dtype=float32)]