<a href="https://colab.research.google.com/github/NileshPatil24-a/Deep_Learning/blob/main/Neural_network_backword_propogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [73]:
model = Sequential()

In [74]:
model.add(Dense(2,activation='linear', input_shape=(2,)))
model.add(Dense(1,activation = 'linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [77]:
model.build(input_shape=(None, 2))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29 (120.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

In [78]:
model.get_weights()

[array([[ 0.70057356, -0.9988469 ],
        [-0.81550264,  0.01969643]], dtype=float32),
 array([0.02325188, 0.02278475], dtype=float32),
 array([[-0.6830989 ],
        [-0.54850745]], dtype=float32),
 array([-0.02296993], dtype=float32)]

In [79]:
X = df.iloc[:,:2].values
y = df.iloc[: ,-1].values

In [80]:
X = X.astype(np.float32)
y = y.astype(np.float32)


In [81]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [82]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)

In [83]:
model.compile(
    optimizer = 'adam',
    loss= 'mean_squared_error',
    metrics=['mae']
)

In [84]:
model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=1,
    verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1865 - mae: 0.3406  
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4451 - mae: 0.5977 
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2314 - mae: 0.4223
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1367 - mae: 0.3248 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2919 - mae: 0.4837 
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2567 - mae: 0.4501 
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1092 - mae: 0.2659 
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1450 - mae: 0.3347
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1447 - mae: 0.3312
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1801 - mae: 0.3894
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1439 - mae: 0.3236
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1039 - mae: 0.2234    
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms

In [85]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.1469 - mae: 0.3832


[0.14686283469200134, 0.3832268714904785]