<a href="https://colab.research.google.com/github/NileshPatil24-a/Deep_Learning/blob/main/zero_Intialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])

In [8]:
df.sample(5)

sepal_length  sepal_width  petal_length  petal_width  species
141           6.9          3.1           5.1          2.3        2
40            5.0          3.5           1.3          0.3        0
134           6.1          2.6           5.6          1.4        2
79            5.7          2.6           3.5          1.0        1
103           6.3          2.9           5.6          1.8        2

In [9]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [60]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1:].values

In [61]:
model = Sequential()
model.add(Dense(3, activation="relu", input_dim=4))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [62]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 3)              │            15 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

In [63]:
model.get_weights()

[array([[-0.8779955 , -0.26268935,  0.661006  ],
        [-0.44357276,  0.69687355, -0.7176471 ],
        [-0.42784777, -0.816444  , -0.5970584 ],
        [ 0.82398355,  0.67247105,  0.8340719 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0.9923929 ],
        [0.75239825],
        [0.28183496]], dtype=float32),
 array([0.], dtype=float32)]

In [64]:
initial_weights = model.get_weights()

In [65]:
initial_weights[0] = np.zeros(model.get_weights()[0].shape)
initial_weights[1] = np.zeros(model.get_weights()[1].shape)
initial_weights[2] = np.zeros(model.get_weights()[2].shape)
initial_weights[3] = np.zeros(model.get_weights()[3].shape)

In [66]:
model.set_weights(initial_weights)

In [67]:
model.get_weights()

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0.],
        [0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

In [68]:
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [69]:
history = model.fit(X,y, epochs=100, validation_split=0.2)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.4198 - loss: 0.6929 - val_accuracy: 0.0000e+00 - val_loss: 0.6872
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4333 - loss: 0.6920 - val_accuracy: 0.0000e+00 - val_loss: 0.6817
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3937 - loss: 0.6913 - val_accuracy: 0.0000e+00 - val_loss: 0.6765
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4604 - loss: 0.6898 - val_accuracy: 0.0000e+00 - val_loss: 0.6711
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4792 - loss: 0.6890 - val_accuracy: 0.0000e+00 - val_loss: 0.6658
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4448 - loss: 0.6885 - val_accuracy: 0.0000e+00 - val_loss: 0.6604
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4021 - loss: 0.6881 - val_accuracy: 0.0000e+00 - val_loss: 0.6551
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4271 - loss: 0.6868 - val_

In [70]:
model.get_weights()

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0.],
        [0.],
        [0.]], dtype=float32),
 array([0.32536435], dtype=float32)]